services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  front:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./Front:/usr/share/nginx/html
    depends_on:
      - back
